---
- name: set admin group sudo setting
  template:
    src: admin.j2
    dest: /etc/sudoers.d/admin.j2
    validate: '/usr/sbin/visudo -cf %s'
- name: add user
  user:
    name: "{{ item.name }}"
    password: "{{ item.password|default(omit) }}"
    shell: "{{ item.shell|default(omit) }}"
  with_items: "{{ common_users }}"
- name: set user authorized_key setting
  authorized_key:
    user: "{{ item.name }}"
    key: "https://github.com/{{ item.name }}.keys"
  with_items: "{{ common_users }}"
- name: add admin user to admin group
  user:
    name: "{{ item.name}}"
    groups: adm
    append: yes
  with_items: "{{ common_users|selectattr('admin', 'defined')|selectattr('admin', 'equalto', true)|list }}"
- name: install common packages
  apt:
    name: "{{ item }}"
  with_items: "{{ common_packages }}"
- name: install ufw
  apt:
    name: ufw
- name: set ufw policy
  ufw:
    state: enabled
    policy: deny
- name: install etckeeper
  apt:
    name: etckeeper
- name: set ufw ssh role
  ufw:
    rule: limit
    port: ssh
    proto: tcp
- name: install fail2ban
  apt:
    name: fail2ban
- name: create fail2ban setting
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban
- name: ufw is active and enabled on system startup
  systemd:
    name: ufw
    state: started
    enabled: yes
- name: fail2ban is active and enabled on system startup
  systemd:
    name: fail2ban
    state: started
    enabled: yes
