---
- name: install aptitude package
  apt:
    name: aptitude
- name: set hostname
  hostname:
    name: "{{ common_hostname }}"
  tags:
    - hostname
- name: manage group and user
  import_tasks: user.yml
  tags:
    - user
    - group
- name: check ansible manage cron job file
  stat:
    path: /etc/cron.d/ansible_management_job
  register: result
- name: create ansible manage cron job file
  file:
    path: /etc/cron.d/ansible_management_job
    state: touch
  when: not result.stat.exists
- name: setup ssh
  import_tasks: ssh.yml
  tags:
    - ssh
- name: setup sudo
  import_tasks: sudo.yml
  tags:
    - sudo
- name: install etckeeper
  apt:
    name: etckeeper
- name: install common packages
  apt:
    name: "{{ item }}"
  with_items: "{{ common_packages }}"
- name: setup ufw
  import_tasks: ufw.yml
  tags:
    - ufw
- name: setup fail2ban
  import_tasks: fail2ban.yml
  tags:
    - fail2ban
