---
- name: manage group
  group:
    name: "{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - groups
    - flags:
        skip_missing: yes
- name: manage user
  user:
    name: "{{ item.name }}"
    password: "{{ item.password|default(omit) }}"
    shell: "{{ item.shell|default(omit) }}"
    home: "{{ item.home|default(omit) }}"
    groups: "{{ item.groups|default(omit) }}"
    group: "{{ item.group|default(omit) }}"
    comment: "{{ item.comment|default(omit) }}"
    system: "{{ item.system|default(false) }}"
    uid: "{{ item.uid|default(omit) }}"
    state: "{{ 'present' if item.state|default(true) else 'absent' }}"
  with_items: "{{ users }}"
- name: add authorized key
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ users }}"
    - authorized_keys
    - flags:
        skip_missing: yes
- name: install common packages
  yum:
    name: "{{ item }}"
  with_items: "{{ common_packages }}"
- name: install firewalld
  yum:
    name: firewalld
- name: firewalld is active and enabled on system startup
  systemd:
    name: firewalld
    state: started
    enabled: yes
- name: install etckeeper
  yum:
    name: etckeeper
    enablerepo: epel
- name: initilize etckeeper
  command: etckeeper init
  args:
    chdir: /etc
    creates: /etc/.git
  register: result
- name: initial commit
  command: etckeeper commit "Initial commit"
  when: result|changed
- name: install fail2ban
  yum:
    name: fail2ban
    enablerepo: epel
- name: create fail2ban setting
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban
- name: fail2ban is active and enabled on system startup
  systemd:
    name: fail2ban
    state: started
    enabled: yes
