---
- name: install ufw
  apt:
    name: ufw
- name: ufw is active and enabled on system startup
  systemd:
    name: ufw
    enabled: true
    state: started
- name: allow ssh port
  ufw:
    rule: limit
    port: "{{ common_ssh_port | string }}"
    proto: tcp
- name: enable ufw and set default policy
  ufw:
    logging: "on"
    state: enabled
    policy: deny
