---
- name: manage group
  group:
    name: "{{ item.name }}"
    state: "{{ 'absent' if item.remove|default(false) else 'present' }}"
  with_items: "{{ common_groups }}"
  tags:
    - group
- name: manage user
  user:
    name: "{{ item.name }}"
    password: "{{ item.password|default(omit) }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
    groups: "{{ item.groups|default(omit) }}"
    state: "{{ 'absent' if item.remove|default(false) else 'present' }}"
    # `userdel` command `--remove` option
    remove: "{{ item.remove|default(false) }}"
  with_items: "{{ common_users }}"
  tags:
    - user
- name: set authorized keys
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1 }}"
  with_subelements:
    - "{{ common_users|selectattr('remove', 'undefined')|list }}"
    - authorized_keys
    - flags:
      skip_missing: yes
  tags:
    - user
- name: set admin group
  user:
    name: "{{ item.name }}"
    groups: adm
    append: yes
  with_items: "{{ common_users|selectattr('remove', 'undefined')|selectattr('admin', 'defined')|selectattr('admin', 'equalto', true)|list }}"
  tags:
    - user
